cesko-digital/volebni-kalkulacka-2022

- .github/workflows/terraform-apply.yaml
- .github/workflows/terraform-plan.yaml
- infrastructure/aws/newrelic.tf
- infrastructure/aws/variables.tf
Added connector for CloudWatch logs to our AWS infrastructure. I'll add readme after testing.
> NewRelic log ingestion

- frontend/src/components/design-system/typography/BodyText.vue
- frontend/src/components/design-system/typography/ButtonText.vue
- frontend/src/components/design-system/typography/HeadlineText.vue
- frontend/src/components/design-system/typography/LabelText.vue
- frontend/src/components/design-system/typography/TitleText.vue
It should be probably done via [defineComponent](https://vuejs.org/api/general.html#definecomponent) to inherit types.
> Fix inheritance in typography components

- data/kalkulacka/komunalni-2022/123456.json
- data/kalkulacka/komunalni-2022/345678.json
- data/kalkulacka/senatni-2022/51.json
- data/kalkulacka/senatni-2022/61.json
- data/kalkulacka/senatni-2022/71.json
- schemas/question.schema.json
In the PR #27 we have introduced new data model. However it's not matching figma. So lets fix this.
> VK-20: Fix data model to match figma

- frontend/src/components/AvatarComponent.vue
- frontend/src/components/MatchOrderComponent.vue
- frontend/src/components/ResultAvatarComponent.vue
- frontend/src/components/design-system/configurations/avatars-configuration.ts
- frontend/src/components/themes/DefaultTheme.scss
- frontend/src/routes/index/IndexPage.vue
Relates to [VK-109](https://cesko-digital.atlassian.net/jira/software/c/projects/VK/issues/VK-109)
> VK-137 + VK-109 Add avatar

- frontend/vite.config.ts
Allows localhost to fetch data from cloud data directory.
> Added localhost dev proxy for data directory

- frontend/src/components/design-system/other/StepProgress.vue
- frontend/src/components/design-system/style/BackgroundComponent.vue
- frontend/src/components/design-system/style/LogoComponent.vue
- frontend/src/components/design-system/typography/HeadingComponent.vue
Closes Jira issues VK-125, VK-126, VK-127 and  VK-128.
> Add various skeletons

- frontend/src/components/design-system/containers/ContainerComponent.vue
- frontend/src/components/design-system/navigation/NavigationBar.vue
This is a dumb presentational component. It can be used directly in views or wrapped with some smart component using routes etc.
> VK-89 Add navbar

- frontend/src/components/design-system/input/RadioButtonComponent.vue
- frontend/src/components/themes/DefaultTheme.scss
- frontend/src/routes/index/IndexPage.vue
Implements [VK-144](https://cesko-digital.atlassian.net/browse/VK-144), [VK-172](https://cesko-digital.atlassian.net/browse/VK-172) and kind of also [VK-182](https://cesko-digital.atlassian.net/browse/VK-182).
> VK-144 + VK-172 + VK-182 Add radio button

- frontend/src/components/design-system/containers/CardComponent.vue
- frontend/src/components/design-system/typography/HeadingComponent.vue
- frontend/src/routes/question/QuestionCard.vue
- frontend/src/routes/question/QuestionPage.vue
Closes [VK-92](https://cesko-digital.atlassian.net/browse/VK-92). ~Needs #69 first.~
> VK-92 Implement question card

- frontend/src/components/design-system/style/LogoComponent.vue
Pořád si nejsem jistá, že ta velikost je ok. Ve Figmě je text jako svg, můžu to nahradit, pak se ale text v logu nebude zalamovat jako dosud.
Tak se přiznám, že nevím.
> Change logo text

- .mypy.ini
- .pre-commit-config.yaml
- backend/main.py
- data/kalkulacka/calculators.json
- data/kalkulacka/komunalni-2022/123456.json
- data/kalkulacka/komunalni-2022/345678.json
- data/kalkulacka/senatni-2022/10.json
- data/kalkulacka/senatni-2022/13.json
- data/kalkulacka/senatni-2022/16.json
- schemas/calculator.schema.json
- schemas/calculators.schema.json
Result object used for storing/retrieving answers now contains additional attributes:
* `matches` - list of candidates with their score
* `calculator` - calculator to which the results belongs
* `source` - optional, from where the user arrived - `seznam-hp`, `newsletter`, ...
Original PR - #66 
There is also change in the schema which is not backward compatible. We use `name` everywhere but there was `label` in list of calculators. 
OpenAPI: [volebni-kalkulacka-004-openapi.json.txt](https://github.com/KohoVolit/volebni-kalkulacka-2022/files/9524930/volebni-kalkulacka-004-openapi.json.txt)
* store results - `curl -X POST -H "Content-Type: application/json" -d '{"answers": [{"question_id": "aaa", "answer": "AAA"}, {"question_id": "bbb", "answer": "BBBB"}], "matches": [{"candidate": …
> VK-204: Store matches and calculator info as part of results

- frontend/src/components/design-system/input/RadioButtonComponent.vue
- frontend/src/components/design-system/navigation/SecondaryNavigationBar.vue
- frontend/src/components/design-system/typography/BodyText.vue
- frontend/src/routes/district-selection/DistrictSelectionPage.vue
Closes [VK-181](https://cesko-digital.atlassian.net/browse/VK-181).
> VK-181 Implement district selection

- frontend/src/components/design-system/style/LogoComponent.vue
Přidání prokliku a hoveru, zatím jen v podobě monochrome.
> Add hover to logo

- frontend/src/components/design-system/input/ButtonComponent.vue
- frontend/src/routes/index/IndexPage.vue
> Button fixes

- frontend/src/routes/district-selection/DistrictSelectionPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/routes/recap/RecapPage.vue
Added color=blue for buttons in the last step of the tutorial and at the Recap page.
> Fix blue buttons

- frontend/src/assets/breakpoints.scss
- frontend/src/components/design-system/containers/AccordionComponent.vue
- frontend/src/components/design-system/containers/CardComponent.vue
- frontend/src/components/design-system/containers/ContainerComponent.vue
- frontend/src/components/design-system/input/ButtonComponent.vue
- frontend/src/components/design-system/layout/StackComponent.vue
- frontend/src/components/responsivity/ResponsiveWrapper.vue
- frontend/src/components/themes/DefaultTheme.scss
- frontend/src/routes/district-selection/DistrictSelectionPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/routes/question/QuestionBottomBar.vue
- frontend/src/routes/question/QuestionCard.vue
- frontend/src/routes/question/QuestionPage.vue
- frontend/src/routes/recap/RecapPage.vue
- frontend/src/routes/recap/RecapQuestionCard.vue
- frontend/src/routes/result/ResultPage.vue
> Refactor recap buttons

- frontend/src/routes/result/ResultPage.vue
Tohle mně lokálně spravilo pre-commit skript – bylo by dobré ho spravit aji v `main`, ať ty PRs teď nejsou všecky zbytečně červené.
> Fix code formatting to pass pre-commit checks

- frontend/src/routes/result/ResultCandidateCard.vue
Show correct party name for komunalni volby.
> Results Page: Show correct party name

- frontend/src/routes/index/IndexPage.vue
Po merge bude aktivni tlacitko senatnich voleb.
> Homepage - allow senatni volby.

- frontend/src/components/responsivity/EmbedWrapper.vue
> Fix embed wrapper

- frontend/src/components/design-system/containers/DividerComponent.vue
Refactor divider so that it:
- supports different weight
- supports dotted and dashed style
- supports color prop
- can be vertical (auto-grows to 100%)
- has no margin nor padding or width/height
> Refactor divider

- frontend/src/routes/index/IndexPage.vue
> Use navigation bar component again on home page

- data/kalkulacka/komunalni-2022/549240.json
- data/kalkulacka/komunalni-2022/554481.json
- data/kalkulacka/komunalni-2022/554791.json
- data/kalkulacka/senatni-2022/10.json
Newly generated data
* `make generate-data` - to generate new data
* `git commit -a` - to apply pre-commit hooks to reformat them
* :moneybag: 
Previous PR: #187
> Generating data - 2022-09-16 10:00

- frontend/package-lock.json
- frontend/package.json
- frontend/parseRestSchemas.js
- frontend/src/common/restApi.ts
- frontend/src/common/resultParser.ts
- frontend/src/common/share.ts
- frontend/src/components/ErrorModal.vue
- frontend/src/components/design-system/input/IconButton.vue
- frontend/src/components/design-system/other/ModalComponent.vue
- frontend/src/main.ts
- frontend/src/routes/result/ResultPage.vue
- frontend/src/routes/result/ResultShareModal.vue
- frontend/src/routes/share/SharePage.vue
- frontend/src/stores/electionStore.ts
- frontend/vercel.json
- frontend/vite.config.ts
The PR will on purpose stay in draft until I change the hardcoded share ulr.
> Social sharing

- data/kalkulacka/senatni-2022/46.json
- data/kalkulacka/senatni-2022/73.json
Newly generated data
* `make generate-data` - to generate new data
* `git commit -a` - to apply pre-commit hooks to reformat them
* :moneybag: 
Previous PR: #201, #214
> Generating data - 2022-09-21 08:30

- frontend/src/components/design-system/input/CheckboxComponent.vue
- frontend/src/routes/result/ResultPage.vue
Checkbox filtering active canidates
> Candidate filter

- backend/converter.py
- data/kalkulacka/calculators.json
- data/kalkulacka/senatni-2022/1.json
- data/kalkulacka/senatni-2022/10.json
- data/kalkulacka/senatni-2022/13.json
- data/kalkulacka/senatni-2022/16.json
- data/kalkulacka/senatni-2022/19.json
- data/kalkulacka/senatni-2022/22.json
- data/kalkulacka/senatni-2022/25.json
- data/kalkulacka/senatni-2022/28.json
- data/kalkulacka/senatni-2022/31.json
- data/kalkulacka/senatni-2022/34.json
- data/kalkulacka/senatni-2022/37.json
- data/kalkulacka/senatni-2022/4.json
- data/kalkulacka/senatni-2022/40.json
- data/kalkulacka/senatni-2022/43.json
- data/kalkulacka/senatni-2022/46.json
- data/kalkulacka/senatni-2022/49.json
- data/kalkulacka/senatni-2022/52.json
- data/kalkulacka/senatni-2022/55.json
- data/kalkulacka/senatni-2022/58.json
- data/kalkulacka/senatni-2022/61.json
- data/kalkulacka/senatni-2022/64.json
- data/kalkulacka/senatni-2022/67.json
- data/kalkulacka/senatni-2022/7.json
- data/kalkulacka/senatni-2022/70.json
- data/kalkulacka/senatni-2022/73.json
- data/kalkulacka/senatni-2022/76.json
- data/kalkulacka/senatni-2022/79.json
Read column `active_candidate` from https://docs.google.com/spreadsheets/d/1ofKCzx8QUSSsH7k_E-QEblJqt45bat8cUKwkpG9qGpQ/edit#gid=0
* `make generate-data` - to generate new data
* `git commit -a` - to apply pre-commit hooks to reformat them
* :moneybag: 
Previous PR: #223
> Read active field from Google sheet

- frontend/src/routes/about-us/AboutUsPage.vue
Povinné informace o podpoře od Arniky
> Arnika text and logo

- frontend/src/components/design-system/layout/MasonryGrid.vue
- frontend/src/routes/index/IndexPage.vue
> November homepage update

- .github/workflows/backend-deploy.yaml
- .github/workflows/data-deploy.yaml
- .github/workflows/frontend.yaml
> Deploy production manually only

- frontend/docs/responsivity.md
- frontend/docs/theming.md
- frontend/src/components/InfoBubble.vue
- frontend/src/components/QuestionCard.vue
- frontend/src/components/design-system/configurations/sizing-and-spacing.ts
- frontend/src/components/design-system/containers/CardComponent.vue
- frontend/src/components/themes/DefaultTheme.scss
- frontend/src/routes/comparison/ComparisonGrid.vue
- frontend/src/routes/index/IndexPage.vue
- frontend/src/routes/recap/RecapQuestionCard.vue
- frontend/src/routes/result/ResultCandidateCard.vue
This brings a new system of sizing & spacing tokens, documents it and implements it in the `CardComponent` (#246 related). The exact values and so will need to settle down during the refactoring of the rest of the components.
Closes #247. #243 & #193 related.
Merge only after #268!
> Refactor & document sizing & spacing

- frontend/index.html
- frontend/src/main.ts
Apparently, it is not [recommended](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#61b8).
> Don't mount App in body tag

- frontend/.env.vercel
- frontend/package-lock.json
- frontend/package.json
- frontend/vercel-build.sh
Creates preview database for each branch during Vercel preview build.
> Build preview for Vercel

- frontend/.env.development
- frontend/.env.test
- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/share.ts
> Setup environment variables

- frontend/api/prisma.ts
- frontend/src/server/prisma.ts
Fix for database URL when in preview mode.
> Fix Vercel preview database

- frontend/vercel-build.sh
~I have no idea what happened.~
Fix a bug/copy + set Vite environment according to the Vercel environment.
> Fix Vercel build script

- frontend/src/components/design-system/containers/TimelineComponent.stories.ts
- frontend/src/components/design-system/containers/TimelineComponent.vue
- frontend/src/components/design-system/containers/TimelineItemComponent.vue
- frontend/src/components/themes/DefaultTheme.scss
> Introduce TimelineComponent

- frontend/src/components/design-system/navigation/NavigationBar.vue
- frontend/src/components/design-system/style/LogoComponent.vue
> Fix logo link

- frontend/src/main.ts
- frontend/src/routes/error/ErrorPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/stores/electionStore.ts
The store has to be now initialized explicitly by calling `store.init()` which now happens only in one place when leaving GuidePage to QuestionPage. The store also deletes itself on page refresh.
> Fix routing and initialization of store

- frontend/src/routes/index/IndexPage.vue
Small fixes in texts (removing "before Xmas", changing candidates)
> update of texts to frontpage

- frontend/package-lock.json
- frontend/package.json
> Add esbuild

- frontend/vercel.json
Fixes SPA routing. Closes #357.
> Fix Vercel config

- frontend/src/routes/guide/GuidePage.vue
> Update guide copy to skip flow

- data/kalkulacka/prezidentske-2023/pro-kazdeho-1-kolo.json
- data/kalkulacka/prezidentske-2023/pro-mladistve-1-kolo.json
- data/kalkulacka/prezidentske-2023/pro-politicke-nadsence-1-kolo.json
- generator/generator/prezidentske_2023.py
> Use hardcoded UUID for calculators

- frontend/src/routes/result/ResultPage.vue
Quick hack to keep the database clean.
> Disable saving answers for old calculators

- frontend/src/routes/index/IndexPage.vue
> Update home page copy

- frontend/src/components/QuestionCard.vue
- frontend/src/components/design-system/layout/StackComponent.vue
- frontend/src/routes/question/QuestionCard.vue
Should hotfix the responsivity issue.
> Wrap tags on question card

- frontend/src/routes/comparison/ComparisonGrid.vue
> Superhotfix comparsion

- frontend/src/routes/question/QuestionPage.vue
> Make answer buttons togglable

- frontend/package.json
> Fix wrong `vercel dev` config path

- frontend/src/components/design-system/navigation/NavigationBar.stories.ts
- frontend/src/components/design-system/navigation/NavigationBar.vue
- frontend/src/components/design-system/other/AvatarComponent.vue
- Login / Signup buttons when signed-out or avatar if logged-in
- Initials from name feature added to AvatarComponent
> Add Sign-in / Login buttons to NavigationBar

- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/resultParser.ts
Keep same candidate order when switching between results and comparison (even for candidates with the same score).  The seed is randomized on page reload.
> Keep random order consistent across pages

- frontend/src/components/design-system/layout/StackComponent.vue
- frontend/src/routes/index/IndexPage.vue
Static text for now, we can load it in real-time from the database later.
> Add completion count

- frontend/src/routes/question/QuestionPage.vue
> Add labels to question navigation buttons

- frontend/src/components/FooterMultiWord.vue
- frontend/src/routes/about-elections/AboutElectionsPage.vue
> Add presidential election to about elections page

- frontend/src/components/design-system/layout/StackComponent.vue
- frontend/src/components/design-system/navigation/NavigationBar.stories.ts
- frontend/src/components/design-system/navigation/NavigationBar.vue
- frontend/src/main.ts
- frontend/src/routes/index/IndexPage.vue
- frontend/src/routes/profile/LoginPageVue.vue
- frontend/src/routes/profile/ProfileCardComponent.vue
- frontend/src/routes/profile/ProfilePage.vue
- frontend/src/routes/profile/RegisterPageVue.vue
- frontend/src/routes/profile/SocialMediaConnectComponent.vue
- frontend/src/stores/userStore.ts
This PR implements the basic login flow for OAuth providers on frontend:
- adds login / logout button to the navigation bar on home page
- adds login page
- adds sign up page
- adds profile page
Closes #287.
> Add basic login flow

- frontend/src/common/restApi.ts
- frontend/src/components/__tests__/utilities/embedding/EmbedProvider.spec.ts
- frontend/src/components/__tests__/utilities/embedding/WebProvider.spec.ts
- frontend/src/components/utilities/embedding/WebProvider.vue
- frontend/src/main.ts
- frontend/src/routes/profile/ProfileCardComponent.vue
- frontend/src/routes/result/ResultPage.vue
- frontend/src/stores/electionStore.ts
- frontend/src/stores/userStore.ts
Updates saving answers so that it supports signed in user instead of update token.
> Add signed in user support to answers saving

- frontend/.env.development
- frontend/api/auth/index.ts
- frontend/src/routes/profile/LoginPageVue.vue
- frontend/src/routes/profile/RegisterPageVue.vue
- frontend/src/routes/profile/SocialMediaConnectComponent.vue
- frontend/src/routes/result/ResultPage.vue
Adds link to sign up on the results page, which then redirects to shared results after sign up.
> Save answers after sign up

- data/kalkulacka/prezidentske-2023/pro-kazdeho.json
- data/kalkulacka/prezidentske-2023/pro-mlade.json
- data/kalkulacka/prezidentske-2023/pro-nadsence.json
> Mark all candidates except Středula as active

- frontend/.prettierrc.yaml
See un-ts/prettier#249 for more details, probably a bug in Prettier.
> Hotfix Prettier dotfiles resolution

- frontend/index.html
Complained at https://developers.facebook.com/tools/debug/?q=www.volebnikalkulacka.cz
> Add missing `fb:app_id` meta tag

- data/example/volebnikalkulacka.cz/doprava-v-praze/candidates.json
- data/example/volebnikalkulacka.cz/doprava-v-praze/organizations.json
- data/example/volebnikalkulacka.cz/doprava-v-praze/persons.json
- data/example/volebnikalkulacka.cz/green-deal/pro-experty/candidates.json
- data/example/volebnikalkulacka.cz/green-deal/pro-experty/organizations.json
- data/example/volebnikalkulacka.cz/green-deal/pro-experty/persons.json
- data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/candidates.json
- data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/organizations.json
- data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/persons.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/candidates.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/organizations.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/persons.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/candidates.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/organizations.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/persons.json
- data/schemas/candidate.schema.json
- data/schemas/organization.schema.json
- data/schemas/organizations.schema.json
- data/schemas/package.json
- data/schemas/person.schema.json
- data/schemas/persons.schema.json
- frontend/docs/data.md
Further work on #515, related to #340.
> Add candidates, persons & organizations schemas

- data/example/volebnikalkulacka.cz/doprava-v-praze/questions.json
- data/example/volebnikalkulacka.cz/green-deal/pro-experty/questions.json
- data/example/volebnikalkulacka.cz/green-deal/pro-kazdeho/questions.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/1-kolo/questions.json
- data/example/volebnikalkulacka.cz/prezidentske-2023/2-kolo/questions.json
- data/schemas/question.schema.json
Renaming from old schemas:
- `name` → `title`
- `gist` → `statement`
> Add question attributes to schemas

- frontend/src/routes/about-us/AboutUsPage.vue
> Swap about us page for Slovak version

- frontend/src/common/dataFetch.ts
- frontend/src/common/restApi.ts
- frontend/src/common/resultParser.ts
- frontend/src/components/QuestionCard.vue
- frontend/src/components/design-system/containers/ElectionCardComponent.vue
- frontend/src/routes/comparison/ComparisonGrid.vue
- frontend/src/routes/comparison/ComparisonPage.vue
- frontend/src/routes/district-selection/DistrictSelectionPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/routes/profile/ElectionCardWrapperComponent.vue
- frontend/src/routes/profile/SocialMediaConnectComponent.vue
- frontend/src/routes/question/QuestionCard.vue
- frontend/src/routes/question/QuestionPage.vue
- frontend/src/routes/recap/RecapPage.vue
- frontend/src/routes/recap/RecapQuestionCard.vue
- frontend/src/routes/result/ResultCardContacts.vue
- frontend/src/routes/result/ResultPage.vue
- frontend/src/stores/electionStore.ts
- frontend/src/types/calculator.d.ts
- frontend/src/types/calculators.d.ts
- frontend/src/types/candidate-answer.d.ts
- frontend/src/types/candidate.d.ts
- frontend/src/types/contact.d.ts
- frontend/src/types/election.d.ts
- frontend/src/types/party.d.ts
- frontend/src/types/question.d.ts
Prefix all functions and types related to old schemas with _deprecated_. Should not change or break anything feature wise.
> Deprecate old schemas

- frontend/src/common/dataFetch.ts
- frontend/src/i18n/locales/sk.json
- frontend/src/routes/about-us/AboutUsPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/routes/index/IndexPage.vue
- frontend/src/routes/questions-methodology/QuestionsMethodologyText.md
language fixes - UI (not data)
> Enhance Slovak translations and copy

- frontend/src/i18n/locales/cs.json
- frontend/src/i18n/locales/sk.json
- frontend/src/routes/result/ResultPage.vue
> Fix few more translations

- frontend/cypress.config.js
- frontend/cypress/e2e/components/electionsPage.ts
- frontend/cypress/e2e/components/landingPage.ts
- frontend/cypress/e2e/components/summaryPage.ts
- frontend/cypress/e2e/integrations/flow.cy.ts
Prosím o review na cypress testy. Je spravené hlavné flow s klikaním odpovede "áno" a potom "nie".
> Add E2E tests for Slovak National Council voting calculator

- data/kalkulacka/calculators.json
- data/types/calculator.ts
- frontend/src/common/dataFetch.ts
- frontend/src/common/restApi.ts
- frontend/src/components/design-system/containers/ElectionCardComponent.vue
- frontend/src/main.ts
- frontend/src/routes/comparison/ComparisonPage.vue
- frontend/src/routes/district-selection/DistrictSelectionPage.vue
- frontend/src/routes/guide/GuidePage.vue
- frontend/src/routes/index/IndexPage.vue
- frontend/src/routes/profile/ElectionCardWrapperComponent.vue
- frontend/src/routes/question/QuestionPage.vue
- frontend/src/routes/recap/RecapPage.vue
- frontend/src/routes/result/ResultPage.vue
- frontend/src/routes/share/SharePage.vue
- frontend/src/stores/electionStore.ts
- frontend/src/types/calculators.d.ts
This PR ~~adds~~ hacks support for loading calculator data dynamically.
> Refactor data fetching vol. 1

- data/schemas/calculator.schema.json
- data/schemas/election.schema.json
- data/types/calculator.ts
- data/types/calculators.ts
- data/types/election.ts
- data/types/elections.ts
I forgot to add $defs to properties in #590.
> Fix schemas

- frontend/src/routes/result/ResultPage.vue
This PR brings back comparison for all calculators but National Voting calculator.
> Bring back comparison (still a hack)

- frontend/cypress/e2e/components/landingPage.ts
- frontend/src/routes/index/IndexPage.vue
> Update Slovak home for youth calculator launch

- frontend/src/common/dataFetch.ts
Another hack after #583 and #592.
> Add support for loading images to data fetching
